### ISSUE TITLE
404 error when try to open notebook in myBinder

### ISSUE THREAD

**Issue by smrgeoinfo** [earthcube2021/ec21_balwada_etal#1]
when click on myBinder link from https://earthcube2021.github.io/ec21_book/notebooks/ec21_balwada_etal/README.html, myBinder page gets to 'launching server' then returns a 404 not found.  The link when the 404 comes up is https://hub.gke2.mybinder.org/user/earthcube2021-ec21_balwada_etal-2ama45nf/doc/tree/DB_01_Glider_Viz_Panel.ipynb

**Comment by dhruvbalwada** [comment]
I am getting the same error. I will look into what happened. 

If you click the launch panel app, that should work.

if you want to look at the files then this should work: https://mybinder.org/v2/gh/earthcube2021/ec21_balwada_etal/HEAD

**Comment by dhruvbalwada** [comment]
The link should be fixed now. I will close this.

**Comment by smrgeoinfo** [comment]
I can open DB_01_Glider_Viz_Panel.ipynb with the link on the https://mybinder.org/v2/gh/earthcube2021/ec21_balwada_etal/HEAD page, but the myBinder Link from the Jupyter book still gets a 404.  
the launch panel link works.  from the Jupyter book.

Maybe update the instructions?

**Comment by dhruvbalwada** [comment]
That is weird. I updated the instructions, here is a snapshot:
![Screen Shot 2021-09-30 at 2 47 38 PM](https://user-images.githubusercontent.com/18236610/135513327-17f31dbe-767a-416e-ba91-4c0bba432dce.png)

It has the exact link that works for you. Can you try again?

**Comment by smrgeoinfo** [comment]
I'm still seeing the same problem from the 'Launch binder' link in the Jupyter book. But I think I see the problem. 
the 404 when binder tries to launch server has this URL:
[https://hub.mybinder.turing.ac.uk/user/earthcube2021-ec21_balwada_etal-1lqc6cpg/**doc/tree**/DB_01_Glider_Viz_Panel.ipynb](https://hub.mybinder.turing.ac.uk/user/earthcube2021-ec21_balwada_etal-p3qucz7q/doc/tree/DB_01_Glider_Viz_Panel.ipynb)

the URL when I open  DB_01_Glider_Viz_Panel.ipynb from the [file list](https://mybinder.org/v2/gh/earthcube2021/ec21_balwada_etal/HEAD) is 
[https://hub.mybinder.turing.ac.uk/user/earthcube2021-ec21_balwada_etal-1lqc6cpg/**notebooks**/DB_01_Glider_Viz_Panel.ipynb](https://hub.mybinder.turing.ac.uk/user/earthcube2021-ec21_balwada_etal-1lqc6cpg/notebooks/DB_01_Glider_Viz_Panel.ipynb)

if I change /**doc/tree**/ to /**notebooks**/ in the URL that's getting the 404, the notebook opens.

**Comment by dhruvbalwada** [comment]
The problem might be that the Jupyter book is not updating the links by just changing them here in the repo, maybe a re-rendering of the book is needed. If you go to the book and look at the link the button takes you to, you will notice that is the old link (what you reported was not working) that was in the repo. 

I assume @fils knows about this more.

**Comment by smrgeoinfo** [comment]
I pinged @fils to see if he has any ideas...
